##################################
DOP_HOME     := $(realpath $(PWD)/../../..)
PATH         := $(PATH):$(DOP_HOME)/dvc/bin

SVN_ROOT     := $(realpath $(PWD)/..)/PROJ_SVN
SVN_URL      := file://$(SVN_ROOT)

##################################
DESIGN_PROJT := testcase
DESIGN_PHASE := P1-trial
DESIGN_BLOCK := chip
DESIGN_STAGE := 400-APR
DESIGN_VERSN := 2017_0615-xxx
DESIGN_CONTR := place_opt

TEST_FILE    := testfile
TEST_DIR_    := testdir

include $(DOP_HOME)/dvc/etc/make/test.make

