ifndef DESIGN_PROJT
DESIGN_PROJT := testcase
endif
ifndef DESIGN_PHASE
DESIGN_PHASE := P1-trial
endif
ifndef DESIGN_BLOCK
DESIGN_BLOCK := chip
endif
ifndef DESIGN_STAGE
DESIGN_STAGE := 400-APR
endif
ifndef DESIGN_VERSN
DESIGN_VERSN := 2017_0615-xxx
endif
ifndef DESIGN_CONTR
DESIGN_CONTR := place_opt
endif
