PATH	:= $(PATH):$(DOP_HOME)/dvc/bin
TMP_FILE:= tmpfile_`date +%Y%m%d_%H%M%S`

help:
	@echo "PWD    = $(PWD)"
	@echo "CURDIR = $(CURDIR)"
	@echo "SVN_ROOT = $(SVN_ROOT)"
	@echo "Usage:"
	@echo "        make init     "
	@echo "        make project   (create_project)"
	@echo "        make version   (create_version; checkout_version)"
	@echo "        make container (create_container; checkout_container)"
	@echo "        make object   "
	@echo "        make commit   "
	@echo "        make list     "
	@echo ""
	@echo "Usage:  make clean    "
	@echo ""

run:	test
test:
	make init
	make project
	make version
	make container
	make object
	make commit
	make list


init: reset_repository svn
reset_repository:
	@rm -fr $(SVN_ROOT) 

$(SVN_ROOT):
	@mkdir -p $(SVN_ROOT)

svn: $(SVN_ROOT)
	@echo "#---------------------------------------------------"
	@echo "# 0. Initial SVN ROOT"
	@echo "#---------------------------------------------------"
	@echo "SVN_ROOT = $(SVN_ROOT)"
	dvc_set_svn $(SVN_ROOT)

project: init
	@echo "#---------------------------------------------------"
	@echo "# 1. Initial Project"
	@echo "#---------------------------------------------------"
	dvc_create_project	$(DESIGN_PROJT)

version: create_version checkout_version
create_version: $(SVN_ROOT)
	@echo "#---------------------------------------------------"
	@echo "# 2. Create version directory in SVN server"
	@echo "#---------------------------------------------------"
	dvc_create_phase	$(DESIGN_PHASE)
	dvc_create_block	$(DESIGN_BLOCK)
	dvc_create_stage	$(DESIGN_STAGE)
	dvc_create_version	$(DESIGN_VERSN)

checkout: checkout_version
checkout_version:
	@echo "#---------------------------------------------------"
	@echo "# 3 Checkout version"
	@echo "#---------------------------------------------------"
	dvc_checkout_version	$(DESIGN_VERSN) $(DESIGN_STAGE)

container: create_container checkout_container
create_container:
	@echo "#---------------------------------------------------"
	@echo "# 4. Create container"
	@echo "#---------------------------------------------------"
	dvc_create_container	$(DESIGN_CNTNR)

checkout_container:
	@echo "#---------------------------------------------------"
	@echo "# 4. Checkout container"
	@echo "#---------------------------------------------------"
	dvc_checkout_container	$(DESIGN_CNTNR)

object: checkin_object
checkin_object:
	@echo "#---------------------------------------------------"
	@echo "# 5. Checkin file into container"
	@echo "#---------------------------------------------------"
	make add_object
	make copy_object
	make link_object

empty: empty_container
empty_container:
	@echo "#---------------------------------------------------"
	@echo "# 5-0 Empty data in container"
	@echo "#---------------------------------------------------"
	dvc_empty_container 	$(DESIGN_CNTNR)

add: add_object
add_object:
	@echo "#---------------------------------------------------"
	@echo "# 5-1 Add file to container"
	@echo "#---------------------------------------------------"
	@echo "$(TMP_FILE)" > $(TMP_FILE)
	cp -f $(TMP_FILE) .container
	dvc_add_object	$(DESIGN_CNTNR)	$(TMP_FILE)

copy: copy_object
copy_object:
	@echo "#---------------------------------------------------"
	@echo "# 5-2 Copy file to container"
	@echo "#---------------------------------------------------"
	@date +%Y%m%d_%H%M%S >> $(TEST_FILE)
	dvc_copy_object	$(DESIGN_CNTNR)	$(TEST_FILE)
	dvc_copy_object	$(DESIGN_CNTNR)	$(TEST_FILE)  newfile

link: link_object
link_object:
	@echo "#---------------------------------------------------"
	@echo "# 5-3 Link directory to container"
	@echo "#---------------------------------------------------"
	@mkdir -p $(TEST_DIR_)
	@date +%Y%m%d_%H%M%S >> $(TEST_DIR_)/$(TEST_FILE)
	dvc_link_object	$(DESIGN_CNTNR)	$(TEST_DIR_)
	dvc_link_object	$(DESIGN_CNTNR)	$(TEST_DIR_)  newdir

rename: rename_object
rename_object:
	@echo "#---------------------------------------------------"
	@echo "# 5-4 Rename file in container"
	@echo "#---------------------------------------------------"
	@mkdir -p old_$(TEST_DIR_)
	dvc_copy_object	$(DESIGN_CNTNR)	old_$(TEST_DIR_)
	dvc_rename_object	$(DESIGN_CNTNR)	old_$(TEST_DIR_)  new_$(TEST_DIR_)

delete: delete_object
delete_object:
	@echo "#---------------------------------------------------"
	@echo "# 5-5 Remove files in container"
	@echo "#---------------------------------------------------"
	dvc_delete_object	$(DESIGN_CNTNR)	$(TEST_FILE)
	dvc_delete_object	$(DESIGN_CNTNR)	$(TEST_DIR_)

update: update_container
update_container:
	@echo "#---------------------------------------------------"
	@echo "# 5-8 Update change into container"
	@echo "#---------------------------------------------------"
	dvc_update_container	$(DESIGN_CNTNR)


commit: commit_container
commit_container:
	@echo "#---------------------------------------------------"
	@echo "# 5-9 Commit change to SVN server"
	@echo "#---------------------------------------------------"
	dvc_commit_container	$(DESIGN_CNTNR)

list: list_version list_container list_variable
list_version:
	@echo "#---------------------------------------------------"
	@echo "# 6-1 List all data in version"
	@echo "#---------------------------------------------------"
	dvc_list_project
	dvc_list_phase
	dvc_list_block
	dvc_list_stage
	dvc_list_version

list_container:
	@echo "#---------------------------------------------------"
	@echo "# 6-2 List all data in container"
	@echo "#---------------------------------------------------"
	dvc_list_container 

list_variable:
	@echo "#---------------------------------------------------"
	@echo "# 6-3 List all variables"
	@echo "#---------------------------------------------------"
	dvc_set_env --local
	dvc_get_env --local --all


clean: clean_data
clean_data: remove_project
	@rm -fr $(TEST_FILE) $(TEST_DIR_) tmpfile_*
	@rm -fr .dvc .project .dvc_block .dvc_version .container

remove_project: remove_version
	@echo "#---------------------------------------------------"
	@echo "# 7-3. Remove proejct"
	@echo "#---------------------------------------------------"
	dvc_remove_project	$(DESIGN_PROJT)

remove_version: remove_container
	@echo "#---------------------------------------------------"
	@echo "# 7-2. Clean up design version data"
	@echo "#---------------------------------------------------"
	dvc_remove_version	$(DESIGN_VERSN) $(DESIGN_STAGE)
	dvc_remove_stage	$(DESIGN_STAGE)
	dvc_remove_block	$(DESIGN_BLOCK)
	dvc_remove_phase	$(DESIGN_PHASE)

remove_container:
	@echo "#---------------------------------------------------"
	@echo "# 7-1. Clean up container data"
	@echo "#---------------------------------------------------"
	dvc_remove_container	$(DESIGN_CNTNR)

