echo "<table id=report>"
echo "<tr class=header><td colspan=3><h2>dvc://$dvc_path/</h2></td></tr>"
echo "<tr class=title>"
echo "<td>PROJECT</td>"
echo "<td>README</td>"
echo "<td>STATUS</td>"
echo "<tr>"
echo "<td class=col1>"
echo "<a href=../index.htm>$dvc_name</a>"
echo "</td>" 
echo "<td class=col2>" 
echo "<object name=readme type=text/html data=.dvc/README width=300></object>"
echo "</td>" 
echo "<td class=col3> </td>" 
echo "</tr>" 
echo "</table>"

