echo "<table id=report>"
echo "<tr class=header><td colspan=3><h2>dvc://$project/</h2></td></tr>"
echo "<tr class=title>"
echo "<td>PROJECT</td>"
echo "<td>README</td>"
echo "<td>STATUS</td>"
echo "<tr>"
echo "<td class=col1><pre>"
echo "<a href=../../index.htm>$project</a>"
echo "</pre></td>" 
echo "<td class=col2><pre>" 
echo "<object name=readme type=text/html data=README></object>"
echo "</pre></td>" 
echo "<td class=col3> </td>" 
echo "</tr>" 
echo "</table>"

