DOP_HOME     := $(HOME)/DOP_HOME
SVN_ROOT     := $(DOP_HOME)/PROJ_SVN

DESIGN_PROJT := testcase
DESIGN_PHASE := P1-trial
DESIGN_BLOCK := chip

SRC_STAGE    := S00-INIT_DATA
SRC_VERSN    := 2017_0610-xxx

DST_STAGE    := S40-APR
DST_VERSN    := 2017_0615-xxx

TEST_FILE    := testfile
TEST_DIR_    := testdir

include $(DOP_HOME)/dvc/etc/mak/makefile.test

