##################################
DOP_HOME     := $(realpath $(PWD)/../..)
SVN_ROOT     := $(DOP_HOME)/PROJ_SVN

##################################
DESIGN_PROJT := testcase
DESIGN_PHASE := P1-trial
DESIGN_BLOCK := chip
DESIGN_STAGE := S40-APR
DESIGN_VERSN := 2017_0615-xxx
DESIGN_CNTNR := place_opt

TEST_FILE    := testfile
TEST_DIR_    := testdir

include $(DOP_HOME)/dvc/etc/mak/makefile.design
include $(DOP_HOME)/dvc/etc/mak/makefile.test
